# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Dana Blog"
description: > # this means to ignore newlines until "email:"
   A mountain needn't be high;

It is famous so long as there is a deity on it.

email: xiong-wei@hotmail.com
#blog logo
logo: "/assets/images/panda_logo.png"
# blog cover
cover: "/assets/images/header_img.jpg"

name: 'Danna'
author: 'Danna Chen'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	http://weibo.com/521213101
#    desc: Follow me on Weibo
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/chendanna
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/u/0/111796302075229377765/posts
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
